"""empty message

Revision ID: a343e75397d2
Revises: 5d9a8eddf206
Create Date: 2020-01-15 15:12:15.662141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a343e75397d2'
down_revision = '5d9a8eddf206'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'yt_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('yt_link', sa.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
